product-name = "bamboo"
version = "0.1.0"
identifier = "com.bieyuanxi.bamboo.app"

[build]
before-dev-command = "bun run dev"
dev-url = "http://localhost:1420"
before-build-command = "bun run build"
frontend-dist = "../dist"

[[app.windows]]
title = "bamboo"
width = 800
height = 600
visible = true
# decorations = false

[app.security.csp]


[bundle]
active = true
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
